kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
  - name: clone
    image: drone/git
    environment:
      GIT_URL:
        from_secret: git_url
    commands:
      - git clone $GIT_URL .
      - git checkout $DRONE_COMMIT

  - name: fmt
    image: arm64v8/rust:bullseye
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check

  - name: clippy
    image: arm64v8/rust:bullseye
    commands:
      - rustup component add clippy
      - cargo clippy --lib -- -D warnings -W clippy::pedantic

  - name: test
    image: arm64v8/rust:bullseye
    commands:
      - cargo test --all
