kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
  - name: clone
    image: drone/git
    commands:
      - git clone http://100.67.82.99:3000/osef/Rhythm-Open-Exchange.git .
      - git checkout $DRONE_COMMIT

  - name: test
    image: arm64v8/rust:bullseye
    commands:
      - cargo test

  - name: clippy
    image: arm64v8/rust:bullseye
    commands:
      - rustup component add clippy
      - cargo clippy -- -D warnings

  - name: fmt
    image: arm64v8/rust:bullseye
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check
