[workspace]
members = [
    "crates/rox",
    "crates/macros",
    "crates/formats",
    "crates/analysis",
    "crates/cli",
    "crates/uniffi",
    "crates/test-utils",
]
resolver = "2"

[workspace.package]
version = "0.7.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Glubus/rhythm-open-exchange"

[workspace.dependencies]
rstest = "0.26.1"
rox = { path = "crates/rox" }
rox-macros = { path = "crates/macros" }
rox-formats = { path = "crates/formats" }
rox-analysis = { path = "crates/analysis" }
rox-test-utils = { path = "crates/test-utils" }
