// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_CLONE_ROXCHART
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_CLONE_ROXCHART
void*_Nonnull uniffi_rox_ffi_fn_clone_roxchart(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FREE_ROXCHART
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FREE_ROXCHART
void uniffi_rox_ffi_fn_free_roxchart(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_CONSTRUCTOR_ROXCHART_NEW
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_CONSTRUCTOR_ROXCHART_NEW
void*_Nonnull uniffi_rox_ffi_fn_constructor_roxchart_new(uint8_t key_count, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_BPM
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_BPM
void uniffi_rox_ffi_fn_method_roxchart_add_bpm(void*_Nonnull ptr, int64_t time_us, float bpm, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_BURST
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_BURST
void uniffi_rox_ffi_fn_method_roxchart_add_burst(void*_Nonnull ptr, int64_t time_us, int64_t duration_us, uint8_t column, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_HOLD
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_HOLD
void uniffi_rox_ffi_fn_method_roxchart_add_hold(void*_Nonnull ptr, int64_t time_us, int64_t duration_us, uint8_t column, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_MINE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_MINE
void uniffi_rox_ffi_fn_method_roxchart_add_mine(void*_Nonnull ptr, int64_t time_us, uint8_t column, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_SV
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_SV
void uniffi_rox_ffi_fn_method_roxchart_add_sv(void*_Nonnull ptr, int64_t time_us, float scroll_speed, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_TAP
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ADD_TAP
void uniffi_rox_ffi_fn_method_roxchart_add_tap(void*_Nonnull ptr, int64_t time_us, uint8_t column, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ARTIST
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_ARTIST
RustBuffer uniffi_rox_ffi_fn_method_roxchart_artist(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_AUDIO_FILE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_AUDIO_FILE
RustBuffer uniffi_rox_ffi_fn_method_roxchart_audio_file(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_BPM_MAX
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_BPM_MAX
double uniffi_rox_ffi_fn_method_roxchart_bpm_max(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_BPM_MIN
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_BPM_MIN
double uniffi_rox_ffi_fn_method_roxchart_bpm_min(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_BPM_MODE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_BPM_MODE
double uniffi_rox_ffi_fn_method_roxchart_bpm_mode(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_CLEAR_NOTES
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_CLEAR_NOTES
void uniffi_rox_ffi_fn_method_roxchart_clear_notes(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_CLEAR_TIMING_POINTS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_CLEAR_TIMING_POINTS
void uniffi_rox_ffi_fn_method_roxchart_clear_timing_points(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_CREATOR
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_CREATOR
RustBuffer uniffi_rox_ffi_fn_method_roxchart_creator(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_DENSITY
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_DENSITY
RustBuffer uniffi_rox_ffi_fn_method_roxchart_density(void*_Nonnull ptr, uint64_t segments, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_DIFFICULTY
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_DIFFICULTY
RustBuffer uniffi_rox_ffi_fn_method_roxchart_difficulty(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_DURATION_SECONDS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_DURATION_SECONDS
double uniffi_rox_ffi_fn_method_roxchart_duration_seconds(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_GET_NOTES
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_GET_NOTES
RustBuffer uniffi_rox_ffi_fn_method_roxchart_get_notes(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_GET_TIMING_POINTS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_GET_TIMING_POINTS
RustBuffer uniffi_rox_ffi_fn_method_roxchart_get_timing_points(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_HASH
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_HASH
RustBuffer uniffi_rox_ffi_fn_method_roxchart_hash(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_HIGHEST_DRAIN_TIME
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_HIGHEST_DRAIN_TIME
double uniffi_rox_ffi_fn_method_roxchart_highest_drain_time(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_HIGHEST_NPS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_HIGHEST_NPS
double uniffi_rox_ffi_fn_method_roxchart_highest_nps(void*_Nonnull ptr, double window_size_s, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_IS_COOP
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_IS_COOP
int8_t uniffi_rox_ffi_fn_method_roxchart_is_coop(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_KEY_COUNT
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_KEY_COUNT
uint8_t uniffi_rox_ffi_fn_method_roxchart_key_count(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_LOWEST_NPS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_LOWEST_NPS
double uniffi_rox_ffi_fn_method_roxchart_lowest_nps(void*_Nonnull ptr, double window_size_s, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_NOTE_COUNT
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_NOTE_COUNT
uint64_t uniffi_rox_ffi_fn_method_roxchart_note_count(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_NOTES_HASH
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_NOTES_HASH
RustBuffer uniffi_rox_ffi_fn_method_roxchart_notes_hash(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_NPS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_NPS
double uniffi_rox_ffi_fn_method_roxchart_nps(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_OFFSET
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_OFFSET
int64_t uniffi_rox_ffi_fn_method_roxchart_offset(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_ARTIST
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_ARTIST
void uniffi_rox_ffi_fn_method_roxchart_set_artist(void*_Nonnull ptr, RustBuffer artist, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_AUDIO_FILE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_AUDIO_FILE
void uniffi_rox_ffi_fn_method_roxchart_set_audio_file(void*_Nonnull ptr, RustBuffer audio_file, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_COOP
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_COOP
void uniffi_rox_ffi_fn_method_roxchart_set_coop(void*_Nonnull ptr, int8_t is_coop, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_CREATOR
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_CREATOR
void uniffi_rox_ffi_fn_method_roxchart_set_creator(void*_Nonnull ptr, RustBuffer creator, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_DIFFICULTY
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_DIFFICULTY
void uniffi_rox_ffi_fn_method_roxchart_set_difficulty(void*_Nonnull ptr, RustBuffer difficulty, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_OFFSET
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_OFFSET
void uniffi_rox_ffi_fn_method_roxchart_set_offset(void*_Nonnull ptr, int64_t offset_us, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_TITLE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SET_TITLE
void uniffi_rox_ffi_fn_method_roxchart_set_title(void*_Nonnull ptr, RustBuffer title, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SHORT_HASH
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_SHORT_HASH
RustBuffer uniffi_rox_ffi_fn_method_roxchart_short_hash(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_TIMINGS_HASH
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_TIMINGS_HASH
RustBuffer uniffi_rox_ffi_fn_method_roxchart_timings_hash(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_TITLE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_TITLE
RustBuffer uniffi_rox_ffi_fn_method_roxchart_title(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_VALIDATE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_METHOD_ROXCHART_VALIDATE
void uniffi_rox_ffi_fn_method_roxchart_validate(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_AUTO_CONVERT
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_AUTO_CONVERT
void uniffi_rox_ffi_fn_func_auto_convert(RustBuffer input, RustBuffer output, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_DECODE_CHART
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_DECODE_CHART
void*_Nonnull uniffi_rox_ffi_fn_func_decode_chart(RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_DECODE_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_DECODE_FROM_BYTES
void*_Nonnull uniffi_rox_ffi_fn_func_decode_from_bytes(RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_DECODE_FROM_STRING
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_DECODE_FROM_STRING
void*_Nonnull uniffi_rox_ffi_fn_func_decode_from_string(RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_ENCODE_CHART
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_FN_FUNC_ENCODE_CHART
void uniffi_rox_ffi_fn_func_encode_chart(void*_Nonnull chart, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_rox_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_rox_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUSTBUFFER_FREE
void ffi_rox_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_rox_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_U8
void ffi_rox_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_U8
void ffi_rox_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_U8
void ffi_rox_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_rox_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_I8
void ffi_rox_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_I8
void ffi_rox_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_I8
void ffi_rox_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_rox_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_U16
void ffi_rox_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_U16
void ffi_rox_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_U16
void ffi_rox_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_rox_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_I16
void ffi_rox_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_I16
void ffi_rox_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_I16
void ffi_rox_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_rox_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_U32
void ffi_rox_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_U32
void ffi_rox_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_U32
void ffi_rox_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_rox_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_I32
void ffi_rox_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_I32
void ffi_rox_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_I32
void ffi_rox_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_rox_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_U64
void ffi_rox_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_U64
void ffi_rox_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_U64
void ffi_rox_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_rox_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_I64
void ffi_rox_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_I64
void ffi_rox_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_I64
void ffi_rox_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_rox_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_F32
void ffi_rox_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_F32
void ffi_rox_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_F32
void ffi_rox_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_rox_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_F64
void ffi_rox_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_F64
void ffi_rox_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_F64
void ffi_rox_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_rox_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_POINTER
void ffi_rox_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_rox_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_POINTER
void ffi_rox_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_rox_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_rox_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_rox_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_rox_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_rox_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_POLL_VOID
void ffi_rox_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_rox_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_FREE_VOID
void ffi_rox_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_ROX_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_rox_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_AUTO_CONVERT
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_AUTO_CONVERT
uint16_t uniffi_rox_ffi_checksum_func_auto_convert(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_DECODE_CHART
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_DECODE_CHART
uint16_t uniffi_rox_ffi_checksum_func_decode_chart(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_DECODE_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_DECODE_FROM_BYTES
uint16_t uniffi_rox_ffi_checksum_func_decode_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_DECODE_FROM_STRING
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_DECODE_FROM_STRING
uint16_t uniffi_rox_ffi_checksum_func_decode_from_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_ENCODE_CHART
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_FUNC_ENCODE_CHART
uint16_t uniffi_rox_ffi_checksum_func_encode_chart(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_BPM
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_BPM
uint16_t uniffi_rox_ffi_checksum_method_roxchart_add_bpm(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_BURST
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_BURST
uint16_t uniffi_rox_ffi_checksum_method_roxchart_add_burst(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_HOLD
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_HOLD
uint16_t uniffi_rox_ffi_checksum_method_roxchart_add_hold(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_MINE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_MINE
uint16_t uniffi_rox_ffi_checksum_method_roxchart_add_mine(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_SV
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_SV
uint16_t uniffi_rox_ffi_checksum_method_roxchart_add_sv(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_TAP
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ADD_TAP
uint16_t uniffi_rox_ffi_checksum_method_roxchart_add_tap(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ARTIST
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_ARTIST
uint16_t uniffi_rox_ffi_checksum_method_roxchart_artist(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_AUDIO_FILE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_AUDIO_FILE
uint16_t uniffi_rox_ffi_checksum_method_roxchart_audio_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_BPM_MAX
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_BPM_MAX
uint16_t uniffi_rox_ffi_checksum_method_roxchart_bpm_max(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_BPM_MIN
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_BPM_MIN
uint16_t uniffi_rox_ffi_checksum_method_roxchart_bpm_min(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_BPM_MODE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_BPM_MODE
uint16_t uniffi_rox_ffi_checksum_method_roxchart_bpm_mode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_CLEAR_NOTES
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_CLEAR_NOTES
uint16_t uniffi_rox_ffi_checksum_method_roxchart_clear_notes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_CLEAR_TIMING_POINTS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_CLEAR_TIMING_POINTS
uint16_t uniffi_rox_ffi_checksum_method_roxchart_clear_timing_points(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_CREATOR
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_CREATOR
uint16_t uniffi_rox_ffi_checksum_method_roxchart_creator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_DENSITY
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_DENSITY
uint16_t uniffi_rox_ffi_checksum_method_roxchart_density(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_DIFFICULTY
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_DIFFICULTY
uint16_t uniffi_rox_ffi_checksum_method_roxchart_difficulty(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_DURATION_SECONDS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_DURATION_SECONDS
uint16_t uniffi_rox_ffi_checksum_method_roxchart_duration_seconds(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_GET_NOTES
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_GET_NOTES
uint16_t uniffi_rox_ffi_checksum_method_roxchart_get_notes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_GET_TIMING_POINTS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_GET_TIMING_POINTS
uint16_t uniffi_rox_ffi_checksum_method_roxchart_get_timing_points(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_HASH
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_HASH
uint16_t uniffi_rox_ffi_checksum_method_roxchart_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_HIGHEST_DRAIN_TIME
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_HIGHEST_DRAIN_TIME
uint16_t uniffi_rox_ffi_checksum_method_roxchart_highest_drain_time(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_HIGHEST_NPS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_HIGHEST_NPS
uint16_t uniffi_rox_ffi_checksum_method_roxchart_highest_nps(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_IS_COOP
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_IS_COOP
uint16_t uniffi_rox_ffi_checksum_method_roxchart_is_coop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_KEY_COUNT
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_KEY_COUNT
uint16_t uniffi_rox_ffi_checksum_method_roxchart_key_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_LOWEST_NPS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_LOWEST_NPS
uint16_t uniffi_rox_ffi_checksum_method_roxchart_lowest_nps(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_NOTE_COUNT
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_NOTE_COUNT
uint16_t uniffi_rox_ffi_checksum_method_roxchart_note_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_NOTES_HASH
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_NOTES_HASH
uint16_t uniffi_rox_ffi_checksum_method_roxchart_notes_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_NPS
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_NPS
uint16_t uniffi_rox_ffi_checksum_method_roxchart_nps(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_OFFSET
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_OFFSET
uint16_t uniffi_rox_ffi_checksum_method_roxchart_offset(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_ARTIST
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_ARTIST
uint16_t uniffi_rox_ffi_checksum_method_roxchart_set_artist(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_AUDIO_FILE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_AUDIO_FILE
uint16_t uniffi_rox_ffi_checksum_method_roxchart_set_audio_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_COOP
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_COOP
uint16_t uniffi_rox_ffi_checksum_method_roxchart_set_coop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_CREATOR
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_CREATOR
uint16_t uniffi_rox_ffi_checksum_method_roxchart_set_creator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_DIFFICULTY
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_DIFFICULTY
uint16_t uniffi_rox_ffi_checksum_method_roxchart_set_difficulty(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_OFFSET
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_OFFSET
uint16_t uniffi_rox_ffi_checksum_method_roxchart_set_offset(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_TITLE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SET_TITLE
uint16_t uniffi_rox_ffi_checksum_method_roxchart_set_title(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SHORT_HASH
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_SHORT_HASH
uint16_t uniffi_rox_ffi_checksum_method_roxchart_short_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_TIMINGS_HASH
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_TIMINGS_HASH
uint16_t uniffi_rox_ffi_checksum_method_roxchart_timings_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_TITLE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_TITLE
uint16_t uniffi_rox_ffi_checksum_method_roxchart_title(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_VALIDATE
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_METHOD_ROXCHART_VALIDATE
uint16_t uniffi_rox_ffi_checksum_method_roxchart_validate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_CONSTRUCTOR_ROXCHART_NEW
#define UNIFFI_FFIDEF_UNIFFI_ROX_FFI_CHECKSUM_CONSTRUCTOR_ROXCHART_NEW
uint16_t uniffi_rox_ffi_checksum_constructor_roxchart_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ROX_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_ROX_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_rox_ffi_uniffi_contract_version(void
    
);
#endif

